import os
from flask import Flask, jsonify ,request
from flask_cors import CORS
import mysql.connector
from dotenv import load_dotenv

load_dotenv()          # reads the .env file

app = Flask(__name__)
CORS(app)              # lets your frontend talk to this backend later

def get_db():
    return mysql.connector.connect(
        host=os.getenv("DB_HOST"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        database=os.getenv("DB_NAME")
    )

@app.route('/api/opportunities', methods=['GET'])
def get_all():
    try:
        db = get_db()
        cursor = db.cursor(dictionary=True)
        cursor.execute("SELECT * FROM opportunities")
        rows = cursor.fetchall()
        for row in rows:
            if row["deadline"]:
                row["deadline"] = row["deadline"].isoformat()
        cursor.close()
        db.close()
        return jsonify(rows), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500
@app.route('/api/opportunities/<int:id>', methods=['GET'])
def get_one(id):
    try:
        db=get_db()
        cursor=db.cursor(dictionary=True)
        cursor.execute("SELECT * FROM opportunities WHERE id =%s", (id,))
        row=cursor.fetchone()
        cursor.close()
        db.close()
        if row is None:
            return jsonify({"error": "Opportunity not found"}), 404
        if row["deadline"]:
            row["deadline"] = row["deadline"].isoformat()
        return jsonify(row),200
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/opportunities', methods=['POST'])
def create_opportunity():
    db = None
    cursor = None

    try:
        # Get JSON data sent by the client
        info = request.get_json(silent=True)

        # Check that the request contains a JSON object
        if not isinstance(info, dict):
            return jsonify({
                "error": "A valid JSON object is required"
            }), 400

        # Fields required to create an opportunity
        required_fields = [
            "title",
            "description",
            "research_area",
            "faculty_name",
            "department",
            "required_skills",
            "positions",
            "deadline",
            "status"
        ]

        # Check for missing or empty fields
        for field in required_fields:
            if field not in info or info[field] is None or info[field] == "":
                return jsonify({
                    "error": f"{field} is required"
                }), 400

        # Validate positions
        try:
            positions = int(info["positions"])

            if positions <= 0:
                raise ValueError

        except (ValueError, TypeError):
            return jsonify({
                "error": "positions must be a positive integer"
            }), 400

        # Validate status
        if info["status"] not in ["Open", "Closed"]:
            return jsonify({
                "error": "Status must be Open or Closed"
            }), 400

        # Validate deadline format
        from datetime import date

        try:
            deadline = date.fromisoformat(info["deadline"])
        except (ValueError, TypeError):
            return jsonify({
                "error": "deadline must use YYYY-MM-DD format"
            }), 400

        # Connect to the database
        db = get_db()
        cursor = db.cursor()

        # Insert the new opportunity into MySQL
        query = """
            INSERT INTO opportunities
            (
                title,
                description,
                research_area,
                faculty_name,
                department,
                required_skills,
                positions,
                deadline,
                status
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """

        values = (
            info["title"],
            info["description"],
            info["research_area"],
            info["faculty_name"],
            info["department"],
            info["required_skills"],
            positions,
            deadline,
            info["status"]
        )

        cursor.execute(query, values)
        db.commit()

        # Return the ID generated by MySQL
        return jsonify({
            "message": "Research opportunity created successfully",
            "id": cursor.lastrowid
        }), 201

    except Exception:
        if db is not None:
            db.rollback()

        app.logger.exception("Failed to create research opportunity")

        return jsonify({
            "error": "Unable to create research opportunity"
        }), 500

    finally:
        # Always close database resources
        if cursor is not None:
            cursor.close()

        if db is not None:
            db.close()


    
if __name__ == '__main__':
    app.run(debug=True)